apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-service-account
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
