apiVersion: v1
kind: ConfigMap
metadata:
  name: heketi-topology
  labels:
    app: heketi
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  topology.json: |-
{{ include "topology" . | indent 4 }}
